# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: glinthawk.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fglinthawk.proto\x12\x12glinthawk.protobuf\"\x86\x03\n\x10InitializeWorker\x12\x12\n\nmodel_name\x18\x01 \x01(\t\x12\x13\n\x0bstart_layer\x18\x02 \x01(\r\x12\x11\n\tend_layer\x18\x03 \x01(\r\x12\x18\n\x10\x63oncurrency_size\x18\x04 \x01(\r\x12 \n\x18\x63oncurrency_pre_att_size\x18\x05 \x01(\r\x12\x1c\n\x14\x63oncurrency_att_size\x18\x06 \x01(\r\x12!\n\x19\x63oncurrency_post_att_size\x18\x07 \x01(\r\x12\x1c\n\x14\x63oncurrency_cls_size\x18\x08 \x01(\r\x12\x19\n\x11max_context_count\x18\t \x01(\r\x12\x11\n\trandomize\x18\n \x01(\x08\x12 \n\x18\x63oncurrency_att_cpu_size\x18\x0b \x01(\r\x12\x1d\n\x15max_context_count_cpu\x18\x0c \x01(\r\x12\x15\n\rrandomize_cpu\x18\r \x01(\x08\x12\x15\n\rblobstore_uri\x18\x0e \x01(\t\"$\n\x0eProcessPrompts\x12\x12\n\nprompt_ids\x18\x01 \x03(\t\"%\n\x0fPromptCompleted\x12\x12\n\nprompt_ids\x18\x01 \x03(\t\"\xc0\x02\n\x08SetRoute\x12\x10\n\x08route_id\x18\x01 \x01(\t\x12\x45\n\x10layer_to_address\x18\x02 \x03(\x0b\x32+.glinthawk.protobuf.SetRoute.LayerToAddress\x1a\xda\x01\n\x0eLayerToAddress\x12\x11\n\tlayer_num\x18\x01 \x01(\r\x12\x45\n\x05stage\x18\x02 \x01(\x0e\x32\x36.glinthawk.protobuf.SetRoute.LayerToAddress.ProtoStage\x12\n\n\x02ip\x18\x03 \x01(\t\x12\x0c\n\x04port\x18\x04 \x01(\r\"T\n\nProtoStage\x12\x10\n\x0cPreAttention\x10\x00\x12\r\n\tAttention\x10\x01\x12\x11\n\rPostAttention\x10\x02\x12\x12\n\x0e\x43lassification\x10\x03\"\xd0\x01\n\x0bWorkerStats\x12\x17\n\x0fstates_received\x18\x01 \x01(\x04\x12\x13\n\x0bstates_sent\x18\x02 \x01(\x04\x12\x18\n\x10states_processed\x18\x03 \x01(\x04\x12\x18\n\x10tokens_processed\x18\x04 \x01(\x04\x12\x18\n\x10tokens_generated\x18\x05 \x01(\x04\x12\x19\n\x11prompts_completed\x18\x06 \x01(\x04\x12\x12\n\nbytes_sent\x18\x07 \x01(\x04\x12\x16\n\x0e\x62ytes_received\x18\x08 \x01(\x04\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'glinthawk_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _INITIALIZEWORKER._serialized_start=40
  _INITIALIZEWORKER._serialized_end=430
  _PROCESSPROMPTS._serialized_start=432
  _PROCESSPROMPTS._serialized_end=468
  _PROMPTCOMPLETED._serialized_start=470
  _PROMPTCOMPLETED._serialized_end=507
  _SETROUTE._serialized_start=510
  _SETROUTE._serialized_end=830
  _SETROUTE_LAYERTOADDRESS._serialized_start=612
  _SETROUTE_LAYERTOADDRESS._serialized_end=830
  _SETROUTE_LAYERTOADDRESS_PROTOSTAGE._serialized_start=746
  _SETROUTE_LAYERTOADDRESS_PROTOSTAGE._serialized_end=830
  _WORKERSTATS._serialized_start=833
  _WORKERSTATS._serialized_end=1041
# @@protoc_insertion_point(module_scope)
