# Generated by Django 4.2.6 on 2023-10-24 17:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Prompt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hash", models.CharField(max_length=64)),
                ("container", models.CharField(max_length=256)),
                ("origin", models.CharField(max_length=256, null=True)),
                (
                    "language_model",
                    models.CharField(
                        choices=[
                            ("llama2_7b", "LLaMa2 7B"),
                            ("llama2_7b_chat", "LLaMa2 7B Chat"),
                            ("llama2_70b", "LLaMa2 70B"),
                            ("llama2_70b_chat", "LLaMa2 70B Chat"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (1, "Submitted"),
                            (2, "Preprocessing"),
                            (3, "Preprocessed"),
                            (4, "Completed"),
                        ],
                        default=1,
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("preprocessed_at", models.DateTimeField(null=True)),
                ("completed_at", models.DateTimeField(null=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
