# Generated by Django 4.2.6 on 2023-10-24 21:44

import django.core.validators
from django.db import migrations, models
import prompts.models


class Migration(migrations.Migration):
    dependencies = [
        ("prompts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="job",
            name="url",
        ),
        migrations.AlterField(
            model_name="job",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=prompts.models.job_directory_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["zip"]
                    )
                ],
            ),
        ),
    ]
