# Generated by Django 4.2.6 on 2023-10-24 21:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("prompts", "0002_remove_job_url_alter_job_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="status",
            field=models.IntegerField(
                choices=[
                    (1, "Submitted"),
                    (2, "Processing"),
                    (3, "Processed"),
                    (4, "Completed"),
                    (5, "Failed"),
                ],
                default=1,
            ),
        ),
        migrations.AlterField(
            model_name="prompt",
            name="status",
            field=models.IntegerField(
                choices=[
                    (1, "Submitted"),
                    (2, "Processing"),
                    (3, "Completed"),
                    (4, "Failed"),
                ],
                default=1,
            ),
        ),
    ]
