# Generated by Django 4.2.6 on 2024-01-02 18:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("prompts", "0004_remove_prompt_id_prompt_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="prompt",
            name="queued_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="prompt",
            name="started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="job",
            name="language_model",
            field=models.CharField(
                choices=[
                    ("stories-110m", "Stories 110M"),
                    ("llama2-7b-chat", "LLaMa2 7B Chat"),
                    ("llama2-13b-chat", "LLaMa2 13B Chat"),
                    ("llama2-70b-chat", "LLaMa2 70B Chat"),
                ],
                default="llama2-70b-chat",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="prompt",
            name="status",
            field=models.IntegerField(
                choices=[
                    (1, "Submitted"),
                    (2, "Preprocessed"),
                    (3, "Queued"),
                    (4, "Started"),
                    (5, "Completed"),
                    (6, "Failed"),
                ],
                default=1,
            ),
        ),
    ]
